### PR TITLE
Appveyor

### PR DESCRIPTION
**Pull request by chcg**
- added appveyor config
- corrected build issues
- used multiprocessor builds
- build with VS2017 and renamed proj dir similar to the other npp-plugins 
- added arm64

, see https://ci.appveyor.com/project/chcg/converter/builds/38749202

### CODE REVIEW

**Comment by chcg** [comment]
@donho updated also this plugin for arm64 as it is for current releases bundled with n++

**Review by donho — CHANGES_REQUESTED** [review]
My current Windows SDK version on both dev & build machine is 10.0.17763.0.
Could you restore to this version for vcxproj please?

**Comment by chcg** [comment]
@donho Adapted WinSDK version and also for the mimetools PR.

**Comment by donho** [comment]
@chcg I saw in comment:
> - add multithreaded build option

What's the reason of adding this option?

**Comment by chcg** [comment]
@donho You mean the setting <MultiProcessorCompilation>true</MultiProcessorCompilation>. This speeds up the build by using not just one processor of your CPU, but all of them, if appropriate.

**Comment by donho** [comment]
> Will you also add this project to your appveyor builds to see if the config is working also fine on your side. Or I could also provide a github action to build this if you like to.

OK, it makes sense for the building system - I've compiled from my side on my PC and I believe this project is too small to see the difference.

**Pull request closed without merging**
